services:
  # Main AI Scribe Service
  ai-scribe:
    build: .
    container_name: ai-scribe
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "7860:7860"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./output:/app/output
      - ai-scribe-cache:/app/cache
    environment:
      - HF_TOKEN=${HF_TOKEN:-}
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["python", "api_server.py"]

volumes:
  ai-scribe-cache:
    driver: local 